### ISSUE TITLE
[RFE] Change default config file name to reflect the project name (road-core/service)

### ISSUE THREAD

**Issue by tisnik** [road-core/service#45]
Currently the default config file is named `olsconfig.yaml`. Would be probably better to come with name that reflect the actual project name.

**Comment by r0x0d** [comment]
Looking at the code, it seems that the project is using for the src folder the `ols` still. Should a new ticket be created to change that as well?

**Comment by r0x0d** [comment]
@tisnik what would be the guidance here? Should the file be called something like `roadcore.yaml` or `service.yaml`? Maybe a normal `config.yaml`?

**Comment by r0x0d** [comment]
Hah, maybe it could be `rcsconfig.yaml` :thinking:
